### ISSUE TITLE
For Apple Silicon MPS support

### ISSUE THREAD

**Issue by QueryType** [abgulati/hf-server#1]
This is a great idea and work. For now it seems it does CUDA only. Possible to support MPS for Apple silicon GPUs?
Thanks

**Comment by abgulati** [comment]
It is very much usable on M-silicon as it is, but only for unquantized models as BitsAndBytes is CUDA-only. I will add a CPU-centric quantization method shortly!

**Comment by abgulati** [comment]
For now, to run on Mac, launch with launch-arguments: `python hf_waitress.py --quantize=n`

**Comment by abgulati** [comment]
@QueryType I've addded support for the Quanto-quantization library. If you've install PyTorch with CPU support for Mac via default setup `pip3 install torch torchvision torchaudio`, please try running with `python hf_waitress.py --quantize=quanto --quant_level=int8` or `int4` and share your findings. Thank you!

**Comment by abgulati** [comment]
Of course @QueryType please `git pull origin main` this repo again, or download the `hf_waitress.py` and `pip install quanto`

**Comment by abgulati** [comment]
@QueryType  I've also attempted to add GGUF support since people seem to feel better with it around, please refer to the README and [HF-documentation](https://huggingface.co/docs/transformers/main/en/gguf) and let me know how it goes please

**Comment by QueryType** [comment]
Thanks so much. I will give it a spin.

**Comment by abgulati** [comment]
@QueryType In addition to `Quanto` quantization, `HQQ` and `AWQ` support has been added as well, check README for details and pull latest commit to test: https://github.com/abgulati/hf-waitress?tab=readme-ov-file#quantizing-llms

NOTE: Awaiting update from you for another day before closing this issue.

**Comment by abgulati** [comment]
Several quantization methods added, with support for CPU & Apple-Silicon now included. Resolution steps shared. Closing since no further updates received.
